### PR TITLE
Undo moves

### PR DESCRIPTION
**Pull request by MisinformedDNA**
Adds ability to undo moves in a classical game of chess. 16 tests were added to ensure correct functionality.

NOTE: This has not been explicitly tested against chess variants, but all existing tests still pass.

### CODE REVIEW

**Comment by ProgramFOX** [comment]
Nice! This week I'll look at how it performs on the variants - I believe it will break on some and work on some others - and make changes for them if necessary.

**Comment by ProgramFOX** [comment]
The behavior for variants is as I expected.

Works for: antichess, king of the hill, horde, and racing kings.
Breaks for: crazyhouse (pockets), atomic (explosions), three-check (checks counter). These three throw NotImplementedException for now.

Thanks for the PR!

**Comment by Sopel97** [comment]
Is there a chance that it ends up on nuget?

**Comment by thomas-daniels** [comment]
yes. Thanks for the reminder!

**Comment by thomas-daniels** [comment]
@Sopel97 Sorry for the wait. I uploaded a new version (0.12.0) to NuGet.

**Pull request merged**
