### PR TITLE
Follow coding conventions.

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by ProgramFOX** [comment]
I agree with the changes, but you're only changing 3 lines out of all places where it could be changed, and I don't like the inconsistency it introduces in the codebase.

**Comment by Youssef1313** [comment]
I've fixed that.

**Comment by ProgramFOX** [comment]
Thanks. Could you squash all this into one commit?

**Comment by Youssef1313** [comment]
> 
> 
> Thanks. Could you squash all this into one commit?

Sure. I've made that.

**Comment by ProgramFOX** [comment]
Looks good!

**Pull request merged**
